--liquibase formatted sql

--changeset plingareddy:123-createtable
CREATE TABLE contacts (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(255),
    lastname VARCHAR(255)
);
--rollback DROP TABLE CONTACTS;

--changeset praveen:115-createtable-colors
CREATE TABLE colors (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bcolor VARCHAR,
    fcolor VARCHAR
);
--rollback DROP TABLE COLORS;

--changeset preddy:116-insert-to-colors
INSERT INTO COLORS (bcolor, fcolor)
VALUES
 ('red', 'red'),
 (NULL, 'blue'),
 ('Green', 'NULL')
--rollback DELETE FROM COLORS WHERE bcolor='red' AND fcolor='red';
--rollback DELETE FROM COLORS WHERE bcolor IS NULL AND fcolor='blue';
--rollback DELETE FROM COLORS WHERE bcolor='Green' AND fcolor='NULL';

--changeset balu:117-insert-to-colors
INSERT INTO COLORS (bcolor, fcolor)
VALUES
 ('blue', 'blue')
--rollback DELETE FROM COLORS WHERE bcolor='blue' AND fcolor='blue';